"""改表名

Revision ID: 9eeffdd187d0
Revises: bde1a892a068
Create Date: 2018-06-28 15:58:17.590532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eeffdd187d0'
down_revision = 'bde1a892a068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_thinking_comment_like',
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('thinking_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thinking_comment_id'], ['tb_thinking_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('thinking_comment_id', 'user_id')
    )
    op.create_table('tb_work_comment_like',
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('work_comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.ForeignKeyConstraint(['work_comment_id'], ['tb_work_comment.id'], ),
    sa.PrimaryKeyConstraint('work_comment_id', 'user_id')
    )
    op.drop_table('thinking__comment_like')
    op.drop_table('work__comment_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work__comment_like',
    sa.Column('creat_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('work_comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], name='work__comment_like_ibfk_1'),
    sa.ForeignKeyConstraint(['work_comment_id'], ['tb_work_comment.id'], name='work__comment_like_ibfk_2'),
    sa.PrimaryKeyConstraint('work_comment_id', 'user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('thinking__comment_like',
    sa.Column('creat_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('thinking_comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thinking_comment_id'], ['tb_thinking_comment.id'], name='thinking__comment_like_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], name='thinking__comment_like_ibfk_2'),
    sa.PrimaryKeyConstraint('thinking_comment_id', 'user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_work_comment_like')
    op.drop_table('tb_thinking_comment_like')
    # ### end Alembic commands ###
